version: '3.1'
services:
  api:
    container_name: api
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./api:/code
      - /code/node_modules
    dependbs_on:
      - db
    command: ["npm", "run", "start"]
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - POSTGRES_PORT=2345
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '2345:5432'
    volumes: 
      # zは権限エラー防止のため。 
      - db:/var/lib/postgresql/data:z
volumes:
  db:
    driver: local