version: '3.8'
services:  
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=koyuki
    ports:
      - '2345:5432'
    volumes: 
      # zは権限エラー防止のため。 
      - db:/var/lib/postgresql/data:z
volumes:
  db:
    driver: local